// import "./globals.css";
import type { Metadata } from "next";
import MainLayout from "../components/layouts/MainLayout";
//todo change Meta data here
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RegisterLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <MainLayout>{children}</MainLayout>;
}
